import os

from datasets2016 import data2016, mc2016
from datasets2017 import data2017, mc2017
from datasets2018 import data2018, mc2018
datasetsNames = ["data2018", "mc2018", "data2017", "mc2017", "data2016", "mc2016"]

from checker import checkDatasets
checkDatasets(datasetsNames, globals())

countDataset = {}
for datasetsName in datasetsNames:
    datasets = globals()[datasetsName]
    samples = datasets.keys()
    for sample in samples:
#        print "#### SAMPLE: %s #### "%sample
        for dataset in datasets[sample]:
            command = 'dasgoclient --query "file dataset=%s | count(file) "'%(dataset)
#            print command
            try:
                countDAS = os.popen ( command ).read().split("\n")[0]
                countDAS = int(countDAS.replace("count(file): ",""))
                countDataset[dataset] = countDAS
            except:
                print "ERROR: Probelems with"
                print command
                countDAS = -1
            print dataset, countDAS

file_ = open("datasetFileCount.py","w")
file_.write("### File generated by datasetFileCounter.py ### \n")
file_.write("\n")
file_.write("datasetFileCount = ")
file_.write(str(countDataset).replace(",",",\n"))
file_.write("\n")
file_.write("\n")
file_.close()
